version: "3.7"

services:
  express:
    container_name: "SpentEasy-web"
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    command: "npm run dev"
    volumes:
      - ../../:/app
    ports:
      - "3000:3000"
  db:
    container_name: "SpentEasy-db"
    image: postgres
    volumes:
      - spenteasy-vol:/var/lib/postgresql/data/pgdata
    env_file:
      - ../../.env
    ports:
      - "5432:5432"

volumes:
  spenteasy-vol:
    external: true