version: "3.7"

services:
  express:
    container_name: "SpentEasy-web"
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    command: "npm run dev"
    volumes:
      - ../../:/app
    ports:
      - "3080:3080"
  db:
    container_name: "SpentEasy-db"
    image: postgres
    volumes:
      - spenteasy-vol:/var/lib/postgresql/data/pgdata
    env_file:
      - ../../.env
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin-spent
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5433
    ports:
      - '5433:5433'

volumes:
  spenteasy-vol:
    external: true